### ISSUE TITLE
gitmoji support

### ISSUE THREAD

**Issue by verbumfeit** [mhutchie/vscode-git-graph#104]
**Describe the feature that you'd like**
Resolve gitmoji strings in commit messages and show the images instead. It really helps to categorize commits at a glance.

**Additional context (optional)**
https://github.com/carloscuesta/gitmoji/

**Comment by mhutchie** [comment]
Thanks for this suggestion, this would be great to have!

I was also wanting to add detection of urls in commit messages & the details view body, and make them clickable links. (I just haven't got around to it due to higher priority feature requests).

**Comment by mhutchie** [comment]
This will be available in v1.9.0, which will be released in the next day.

I decided to extend this feature request to support automatic replacement of common Emoji Shortcodes used in Git commits (including all of gitmoji, and also a variety of alternatives). I also implemented a new setting `git-graph.customEmojiShortcodeMappings` that allows new Emoji Shortcodes to be mapped, or override existing mappings.

**Comment by LeoRpc** [comment]
Hi everyone,

Thank you @mhutchie for your extension, I love it!

Apparently some emoji (🧹, 🎁 at least) are still missing on v1.30.0?

![image](https://user-images.githubusercontent.com/26821499/200927633-854625da-5a76-4089-963c-efd98b27a910.png)
