### ISSUE TITLE
Git Graph Unable to load Git Graph. Either the current workspace is not a Git Repository, or the Git executable could not found.

### ISSUE THREAD

**Issue by SmUrF3R5** [mhutchie/vscode-git-graph#21]
**Describe the bug**
Git Graph
Unable to load Git Graph. Either the current workspace is not a Git Repository, or the Git executable could not found.

git.path is defined in the settings file

**What does the bug relate to**
List the area(s) this issue relates to, for example:
- Graph Rendering

**To reproduce**
Steps to reproduce the behaviour:
1. Open a Workspace
2. Click on 'Git Graph' or F1 > Git Graph
3. See error

**Expected behaviour**
I would expect to see a colored graph

**Environment**
 - OS: [Windows 10]
 - Visual Studio Code Version: [1.31.1]

**Screenshots (optional)**
Add any screenshots to help explain your problem.
![error1](https://user-images.githubusercontent.com/25916918/53896193-c1f0de80-3ff0-11e9-9dbb-dcae1d1978a5.JPG)

**Additional context (optional)**
git.path is defined and other git extensions are working GitHistory etc

**Comment by mhutchie** [comment]
Are you trying to view Git Graph in multi-root workspace? If so, is the first root folder a Git repo?

**Comment by oppoic** [comment]
> Are you trying to view Git Graph in multi-root workspace? If so, is the first root folder a Git repo?

Git Graph just work for the first folder in vs code?how to use it in other root folder?

**Comment by mhutchie** [comment]
@oppoic Multi-root workspaces will be fully support in the next release 1.4.1 (available tomorrow), as described in the issue https://github.com/mhutchie/vscode-git-graph/issues/13. I asked this question, as it could explain the issue @SmUrF3R5 was having, as Git Graph currently only displays the first folder in a multi-root workspace.

**Comment by mhutchie** [comment]
@SmUrF3R5 Multi-root support now available in 1.4.1 (which I was alluding to in my previous question). Please update to it, and report back if you are still having an issue.

**Comment by mhutchie** [comment]
@SmUrF3R5 Your value for `git.path` doesn't include `git.exe`. The Visual Studio Code description of the `git.path` setting indicates "Path and filename of the git executable, e.g. C:\Program Files\Git\bin\git.exe (Windows).". Missing `git.exe` would definitely cause the behaviour you're observing. I didn't pick up this discrepancy from your screenshot until writing this comment.

I'm closing this issue as it has been a week and you haven't responded to any of my previous questions asking for additional information, but please reply if it is still not resolved with the first paragraph of this comment, or if your issue is now resolved. I'll reopen this issue if you're still having a problem, but I think the first paragraph will almost certainly solve your issue.

**Comment by GeorgeWells** [comment]
I just experienced this issue and it was because git.path wasn't set in settings.json.

**Comment by avirupdutta** [comment]
how did you fix it?
I have this set in my settings .json
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"
but it still doesn't work :(

**Comment by mhutchie** [comment]
@avirupdutta `git.path` is the "Path and filename of the git executable". You have it set to `bash.exe` when it should be `git.exe`.

**Comment by avirupdutta** [comment]
I also tried putting git.exe in the path of "git.path" but it still doesn't
recognize. So I tried out with bash.exe

**Comment by mhutchie** [comment]
@avirupdutta `git.path` should be `C:\Program Files\Git\bin\git.exe` for you, not `C:\Program Files\Git\bin\bash.exe`.

**Comment by avirupdutta** [comment]
OMG it worked!!!! Thank you so so much :)
It just needed the vscode to be refreshed after I update the `settings.json` file

**Comment by sjw1980** [comment]
In my case. exFat file system isn't fit enough to use git graph in Windows 10. 
I don't know why.
